# config/segmentation_config.yaml

checkpoint_path: 'output/checkpoint/IMISNet-B.pth'
category_weights_path: 'dataloaders/categories_weight.pkl'

# Device & distributed training parameters
device:
  device: "cuda"   # Device to use: "cpu", "cuda:0", etc. (leave null for auto-detection)
  multi_gpu:
    enabled: false
    rank: 0  # GPU rank for distributed training

# Model configuration
model:
  image_size: 1024
  sam_model_type: 'vit_b'  # Could be 'vit_b', 'vit_l', 'vit_h'
  test_mode: true

# Prediction configuration
prediction:
  multimask_output: false

